.PHONY: clean All

All:
	@echo "----------Building project:[ total - Debug ]----------"
	@cd "total" && "$(MAKE)" -f  "total.mk"
clean:
	@echo "----------Cleaning project:[ total - Debug ]----------"
	@cd "total" && "$(MAKE)" -f  "total.mk" clean
